const TRADING_CONSTANT_BUY = "1";
const TRADING_CONSTANT_SELL = "2";

const TRADING_CONSTANT = {
  TRADING_TYPE: {
    [TRADING_CONSTANT_BUY]: "Buy",
    [TRADING_CONSTANT_SELL]: "Sell",
  },
};

export default TRADING_CONSTANT;
